return {
  -- disable trouble
  -- { "folke/noice.nvim", enabled = false },
  -- { "stevearc/conform.nvim", enabled = false },
  -- { "mfussenegger/nvim-lint", enabled = false },
  -- { "folke/flash.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "NMAC427/guess-indent.nvim", enabled = false },
  -- { "echasnovski/mini.pairs", enabled = false },
  -- { "echasnovski/mini.animate", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  -- { "echasnovski/mini.indentscope", enabled = false },
  -- -- { "nvim-treesitter/nvim-treesitter-context", enabled = false },
  -- { "Bekaboo/dropbar.nvim", enabled = false },
  { "ray-x/navigator.lua", enabled = false },
  { "nvimdev/lspsaga.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "stevearc/aerial.nvim", enabled = false },
  { "rcarriga/cmp-dap", enabled = false },
  { "OXY2DEV/markview.nvim", enabled = false },
  -- { "hrsh7th/nvim-cmp", enabled = false },
  -- { "ms-jpq/coq_nvim", enabled = false },
  -- { "ray-x/lsp_signature.nvim", enabled = false },
  -- { "bufferline.nvim", enabled = false },
  -- { "ranjithshegde/ccls.nvim", enabled = false },
  -- { "AlejandroSuero/freeze-code.nvim", enabled = false },
  { "folke/which-key.nvim", optional = true, enabled = false },
  { "windwp/nvim-autopairs", enabled = false },
  -- { "kevinhwang91/nvim-ufo", enabled = false },
  -- { "b0o/incline.nvim", enabled = false },
  { "mrjones2014/smart-splits.nvim", enabled = false },
  { "stevearc/quicker.nvim", enabled = false },
  -- { "tanvirtin/vgit.nvim", enabled = false },
}
